# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_register_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='last_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
    ]
