# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20161216_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='datehired',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
